### ISSUE TITLE
How train linemod or ycb-v?

### ISSUE THREAD

**Issue by johnbhlm** [sh8/RePOSE#1]
Hi, thanks your work, this is a meaningful and interesting. 
but I want to know that  the code update work has been completed? How can I start training?

**Comment by sh8** [comment]
Hi, thank you for your interest in our work!

I definitely plan to release the training code. I'm currently busy with my CVPR submission and coursework, so I can't make time for refactoring and checking the training code compatibility with the latest Pytorch version for a while.
I'm sorry but please stay tuned for the update!

**Comment by phquentin** [comment]
Hi sh8, 
can you already estimate when you will release the training code?

**Comment by sh8** [comment]
Thank you for the comment! Hopefully, it would be in a month or two months!

**Comment by lenaNzrva** [comment]
Hey ! somehow it is possible to run the script for training now?

**Comment by sh8** [comment]
Unfortunately, I keep busy with another project and I still can not make time to release the training code. In fact, it requires some work because I separated the code to extract the PVNet's feature for easy evaluation. I think you can use the almost same training script as [clean-pvnet](https://github.com/zju3dv/clean-pvnet), so I recommend you to check it out if you want to train the model yourself as soon as possible. I will update this issue again when the training code is available!

**Comment by lenaNzrva** [comment]
> Unfortunately, I keep busy with another project and I still can not make time to release the training code. In fact, it requires some work because I separated the code to extract the PVNet's feature for easy evaluation. I think you can use the almost same training script as [clean-pvnet](https://github.com/zju3dv/clean-pvnet), so I recommend you to check it out if you want to train the model yourself as soon as possible. I will update this issue again when the training code is available!

Thank you! I will try
